### ISSUE TITLE
please add reshape layer

### ISSUE THREAD

**Issue by breadbread1984** [gahaalt/pytorch-functional#2]
I find there is no reshape layer in layers.py. please add this frequently used layer. thx

**Comment by gahaalt** [comment]
Thanks for filling the issue. I added the layer and updated PyPI package.

**Comment by breadbread1984** [comment]
thx for your prompt support

**Comment by gahaalt** [comment]
I was thinking about the user experience, since modifying batch size is a rare use case.

So as default `ReshapeLayer` works like this and doesn't alter batch size:
```
from pytorch_functional import Input, layers

x = Input(shape=(32, 32))
x = x(layers.ReshapeLayer(shape=(16, 64)))
x.shape # (None, 16, 64)
```
As you can see, it kept the original batch size as 32 * 32 == 16 * 64


But if you want to modify batch size (a rare use case), you need to use additional argument:
```
from pytorch_functional import Input, layers

x = Input(shape=(32, 32), _batch_size=3)
x = x(layers.ReshapeLayer(shape=(6, 16, 32), batch_size_included=True))
x.shape # (None, 16, 32) but in reality it returns (6, 16, 32)
```

Does it work now as you would expect it to?

**Comment by breadbread1984** [comment]
yes very convenient.
